# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-repo-tracker" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "be964561f97d3d96c0ea069c5b34a0d0a045c0dc3132f64222e6c9bc9e381679"
      url "https://github.com/laszukdawid/git-repo-tracker/releases/download/v#{version}/git-repo-tracker_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b01dc12fe079ffdfcaf769f7d72688ed07edc38c4676f66ba18838d0aa187583"
      url "https://github.com/laszukdawid/git-repo-tracker/releases/download/v#{version}/git-repo-tracker_Darwin_arm64.tar.gz"
    end
  end

  name "git-repo-tracker"
  desc "System-tray tracker for local git repositories"
  homepage "https://github.com/laszukdawid/git-repo-tracker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-repo-tracker"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-repo-tracker"]
  end

  # No zap stanza required

  caveats <<~EOS
    git-repo-tracker is a system-tray app — it has no main window.
    Start it with:
      git-repo-tracker
    then look for the icon in the menu bar. Left-click it for the search
    popover, right-click for the menu.

    Config lives at:
      ~/Library/Application Support/git-repo-tracker/config.yaml
  EOS
end
