# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-repo-tracker" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "ed06d62600ae661cb4bedae83e43a8389c44aeedb3a7d33c506c3eb5e6fecdae"
      url "https://github.com/laszukdawid/git-repo-tracker/releases/download/v#{version}/git-repo-tracker_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f08ebdc837f114a882647ba6ec9979bb74bde886c6e8c7d14ab127bca18b5e2c"
      url "https://github.com/laszukdawid/git-repo-tracker/releases/download/v#{version}/git-repo-tracker_Darwin_arm64.tar.gz"
    end
  end

  name "git-repo-tracker"
  desc "System-tray tracker for local git repositories"
  homepage "https://github.com/laszukdawid/git-repo-tracker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-repo-tracker"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-repo-tracker"]
  end

  # No zap stanza required

  caveats <<~EOS
    git-repo-tracker is a system-tray app — it has no main window.
    Start it with:
      git-repo-tracker
    then look for the icon in the menu bar. Left-click it for the search
    popover, right-click for the menu.

    Config lives at:
      ~/Library/Application Support/git-repo-tracker/config.yaml
  EOS
end
