# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-repo-tracker" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "41e53a92cf0c91ed816c88ec7b8ad23c568e492b498480c3fb9d1adaf88477f7"
      url "https://github.com/laszukdawid/git-repo-tracker/releases/download/v#{version}/git-repo-tracker_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "53c9be4af53d909e173aeee257b847a2b4a6b0f60632fcfa94b04c47efa1cfe9"
      url "https://github.com/laszukdawid/git-repo-tracker/releases/download/v#{version}/git-repo-tracker_Darwin_arm64.tar.gz"
    end
  end

  name "git-repo-tracker"
  desc "System-tray tracker for local git repositories"
  homepage "https://github.com/laszukdawid/git-repo-tracker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-repo-tracker"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-repo-tracker"]
  end

  # No zap stanza required

  caveats <<~EOS
    git-repo-tracker is a system-tray app — it has no main window.
    Start it with:
      git-repo-tracker
    then look for the icon in the menu bar. Left-click it for the search
    popover, right-click for the menu.

    Config lives at:
      ~/Library/Application Support/git-repo-tracker/config.yaml
  EOS
end
