# This file was generated by GoReleaser. DO NOT EDIT.
cask "k8s-tray-forwarder" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "eec033c6a2fc69f537b75b96c1fc6ebcf99ead3cabf5a212452da80c6b469e51"
      url "https://github.com/laszukdawid/k8s-tray-forwarder/releases/download/v#{version}/k8s-tray-forwarder_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c0bfd3aafd05b6345096ab62932d6aa8976f959759f8f6bfd43c6f1687f32d05"
      url "https://github.com/laszukdawid/k8s-tray-forwarder/releases/download/v#{version}/k8s-tray-forwarder_Darwin_arm64.tar.gz"
    end
  end

  name "k8s-tray-forwarder"
  desc "macOS menu-bar app to toggle Kubernetes port-forwards"
  homepage "https://github.com/laszukdawid/k8s-tray-forwarder"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "k8s-tray-forwarder"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/k8s-tray-forwarder"]
  end

  # No zap stanza required

  caveats <<~EOS
    k8s-tray-forwarder is a macOS menu-bar app — it has no main window.
    Start it with:
      k8s-tray-forwarder
    then look for the icon in the menu bar.

    Config lives at:
      ~/Library/Application Support/k8s-tray-forwarder/config.yaml
  EOS
end
