# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminal-agent" do
  version "0.41.1"

  on_macos do
    on_intel do
      sha256 "60ed7cdcf7a63a0e9ef6b76fd646aa2b86b35b41cf9d2fae4cdae9a85016f452"
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v#{version}/terminal-agent_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "33e8dc689c62be93aebac4712d1b1a741c675bc938cacfc92ab88344a0a21d40"
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v#{version}/terminal-agent_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "94f624b23a6cefe0fb312dc2f02b65e8e80868808c30f4a32e48cdf42f7f91df"
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v#{version}/terminal-agent_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b85c21a0e752c03465f6f91d0e5969d938a483928006a3f36629f11043c0d3ab"
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v#{version}/terminal-agent_Linux_arm64.tar.gz"
    end
  end

  name "terminal-agent"
  desc "An LLM Agent to help you from and within the terminal"
  homepage "https://github.com/laszukdawid/terminal-agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent"

  # No zap stanza required

  caveats <<~EOS
    To get started with Terminal Agent:

    1. Set up your API key for your preferred provider:
       export OPENAI_API_KEY=your-key-here
       # or
       export ANTHROPIC_API_KEY=your-key-here

    2. Configure your provider:
       agent config set provider openai
       agent config set model gpt-4o-mini

    3. Start asking questions:
       agent ask "What is a file descriptor?"

    For more information, visit:
      https://laszukdawid.github.io/terminal-agent/

    Pro tip: Set up an alias for quick access:
      alias aa="agent ask"
  EOS
end
