# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminal-agent" do
  version "0.43.0"

  on_macos do
    on_intel do
      sha256 "2700d38c031e2addf49d39699840ad9051270abf0de305f1f99ed3ee6c999bcb"
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v#{version}/terminal-agent_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "134e81d8be02e86ecf62bf5292eb28b028f1949b8a801f455b6a7d2266d34ddc"
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v#{version}/terminal-agent_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a70d77fbdca7449343ade73ca8da1c22b2b98acd22544e6d2a759b7cd63c5a3c"
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v#{version}/terminal-agent_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a5b31c3363a0f2db88e3f9bf4869efacc3ed0b7b471b849bfa1758693e538b34"
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v#{version}/terminal-agent_Linux_arm64.tar.gz"
    end
  end

  name "terminal-agent"
  desc "An LLM Agent to help you from and within the terminal"
  homepage "https://github.com/laszukdawid/terminal-agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent"

  # No zap stanza required

  caveats <<~EOS
    To get started with Terminal Agent:

    1. Set up your API key for your preferred provider:
       export OPENAI_API_KEY=your-key-here
       # or
       export ANTHROPIC_API_KEY=your-key-here

    2. Configure your provider:
       agent config set provider openai
       agent config set model gpt-4o-mini

    3. Start asking questions:
       agent ask "What is a file descriptor?"

    For more information, visit:
      https://laszukdawid.github.io/terminal-agent/

    Pro tip: Set up an alias for quick access:
      alias aa="agent ask"
  EOS
end
