# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminal-agent" do
  version "0.39.5"

  on_macos do
    on_intel do
      sha256 "3544e45882c9013fc8a65d45bfeaae6a53e653d932c91a175863ea3c5186884d"
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v#{version}/terminal-agent_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "32aa5184abf7f78ce90c498f40a4692e85a4f216ccda892e5d1b8fb58933ef43"
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v#{version}/terminal-agent_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b2bda18c6ead9dd9ba81b2a1e7286feef213905562d9fd572a6f371a7dd5ca3c"
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v#{version}/terminal-agent_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "49a4b596d3a6d334eb9756b3f4ec5cf140e6eea87aca979067217cca44d556ef"
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v#{version}/terminal-agent_Linux_arm64.tar.gz"
    end
  end

  name "terminal-agent"
  desc "An LLM Agent to help you from and within the terminal"
  homepage "https://github.com/laszukdawid/terminal-agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent"

  # No zap stanza required

  caveats <<~EOS
    To get started with Terminal Agent:

    1. Set up your API key for your preferred provider:
       export OPENAI_API_KEY=your-key-here
       # or
       export ANTHROPIC_API_KEY=your-key-here

    2. Configure your provider:
       agent config set provider openai
       agent config set model gpt-4o-mini

    3. Start asking questions:
       agent ask "What is a file descriptor?"

    For more information, visit:
      https://laszukdawid.github.io/terminal-agent/

    Pro tip: Set up an alias for quick access:
      alias aa="agent ask"
  EOS
end
