# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerminalAgent < Formula
  desc "An LLM Agent to help you from and within the terminal"
  homepage "https://github.com/laszukdawid/terminal-agent"
  version "0.14.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v0.14.1/terminal-agent_Darwin_x86_64.tar.gz"
      sha256 "880be20613568ba8205113b3078d8dd6321a6d52bee441857a62bfe071f72cc0"

      define_method(:install) do
        bin.install "agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v0.14.1/terminal-agent_Darwin_arm64.tar.gz"
      sha256 "70be45c00645ea5b3982bb82e104dfd4f96a698b52ab32c21ff5a81304725119"

      define_method(:install) do
        bin.install "agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v0.14.1/terminal-agent_Linux_x86_64.tar.gz"
      sha256 "31250bab85e5872263697ac6724cdeb819a70fb470f0d71894f305457276d32e"
      define_method(:install) do
        bin.install "agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v0.14.1/terminal-agent_Linux_arm64.tar.gz"
      sha256 "8ff44a91b16839e66ff9ce8adc466eb38efef5b17c6ac3dfbb8cebf0409b7e3e"
      define_method(:install) do
        bin.install "agent"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Terminal Agent:

      1. Set up your API key for your preferred provider:
         export OPENAI_API_KEY=your-key-here
         # or
         export ANTHROPIC_API_KEY=your-key-here

      2. Configure your provider:
         agent config set provider openai
         agent config set model gpt-4o-mini

      3. Start asking questions:
         agent ask "What is a file descriptor?"

      For more information, visit:
        https://laszukdawid.github.io/terminal-agent/

      Pro tip: Set up an alias for quick access:
        alias aa="agent ask"
    EOS
  end

  test do
    system "#{bin}/agent", "--help"
  end
end
