# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerminalAgent < Formula
  desc "An LLM Agent to help you from and within the terminal"
  homepage "https://github.com/laszukdawid/terminal-agent"
  version "0.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v0.15.0/terminal-agent_Darwin_x86_64.tar.gz"
      sha256 "dd59011bcdd2a6757ca4044cdf904392a5a747617b5e52b7e34e1a9e0f937d83"

      define_method(:install) do
        bin.install "agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v0.15.0/terminal-agent_Darwin_arm64.tar.gz"
      sha256 "aff4f8a2369962b2e28b454c71b9f355ba20fd4f236186c33d53c4b80706f0bd"

      define_method(:install) do
        bin.install "agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v0.15.0/terminal-agent_Linux_x86_64.tar.gz"
      sha256 "f69946c6dfbf67c917657da95f63ac1f49321c88c20412a0ed7c1becd9b56725"
      define_method(:install) do
        bin.install "agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v0.15.0/terminal-agent_Linux_arm64.tar.gz"
      sha256 "61c20cb9f586ee7796547e8e4898ddfa350bc0e0708326da5f7136cc84caa801"
      define_method(:install) do
        bin.install "agent"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Terminal Agent:

      1. Set up your API key for your preferred provider:
         export OPENAI_API_KEY=your-key-here
         # or
         export ANTHROPIC_API_KEY=your-key-here

      2. Configure your provider:
         agent config set provider openai
         agent config set model gpt-4o-mini

      3. Start asking questions:
         agent ask "What is a file descriptor?"

      For more information, visit:
        https://laszukdawid.github.io/terminal-agent/

      Pro tip: Set up an alias for quick access:
        alias aa="agent ask"
    EOS
  end

  test do
    system "#{bin}/agent", "--help"
  end
end
