# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerminalAgent < Formula
  desc "An LLM Agent to help you from and within the terminal"
  homepage "https://github.com/laszukdawid/terminal-agent"
  version "0.12.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v0.12.1/terminal-agent_Darwin_x86_64.tar.gz"
      sha256 "7bda1dae61a7d744148720673c95775af807e8fae34448d690cdfe4808d50fd5"

      define_method(:install) do
        bin.install "agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v0.12.1/terminal-agent_Darwin_arm64.tar.gz"
      sha256 "420e0a09e1a099f0c928eac8013727406a6fc508cfc2f56d87c68a87244a0985"

      define_method(:install) do
        bin.install "agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v0.12.1/terminal-agent_Linux_x86_64.tar.gz"
      sha256 "7523d3a6f3a8a71f35381cf0dd266e40a2efb6ea955bbd1075907c4ed2fa3b32"
      define_method(:install) do
        bin.install "agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/laszukdawid/terminal-agent/releases/download/v0.12.1/terminal-agent_Linux_arm64.tar.gz"
      sha256 "832740310a4d0af99ad23583393d847e1dd59ad012d03bc05d99988c7ccaaed4"
      define_method(:install) do
        bin.install "agent"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Terminal Agent:

      1. Set up your API key for your preferred provider:
         export OPENAI_API_KEY=your-key-here
         # or
         export ANTHROPIC_API_KEY=your-key-here

      2. Configure your provider:
         agent config set provider openai
         agent config set model gpt-4o-mini

      3. Start asking questions:
         agent ask "What is a file descriptor?"

      For more information, visit:
        https://laszukdawid.github.io/terminal-agent/

      Pro tip: Set up an alias for quick access:
        alias aa="agent ask"
    EOS
  end

  test do
    system "#{bin}/agent", "--help"
  end
end
